# meta cluster, I could move prom to app with installing CRDs or even consider moving away from rules and monitors in argocd chart(otherwise I'll have to install rule&serviceMonitor CRDs manually before argo along with namespace)
repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
releases:
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    createNamespace: true
    #version: 27.2.0
    values: [values/prometheus.yaml]
  - name: argo-cd
    namespace: argo-cd
    chart: argo/argo-cd
    createNamespace: true
    #version: 3.29.0
    values: [values/argocd.yaml]